name: edukids
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_fonts: ^4.0.3 # Add this line

flutter:
  uses-material-design: true

  assets:
    - assets/facebook_logo.png
    - assets/google_logo.png
    - assets/google.png
    - assets/facebook.png
    - assets/blender_course.jpeg
    - assets/fullstack.jpeg
    - assets/ui_ux.jpeg
    - assets/backend.jpeg
    - assets/TCourse.jpg
    - assets/github.png
    - assets/profile.png

  fonts:
    - family: poppins
      fonts:
        - asset: fonts/poppins/Poppins-Black.ttf

flutter_native_splash:
  color: "#ffffff" # Warna latar belakang splash screen
  image: assets/TCourse.jpg # Path gambar logo (pastikan gambar ada di folder assets)
  android: true
  ios: true
  web: true
  fullscreen: true
